//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBlog.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZigBlog.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms (click here to read).
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terms need to be accepted.
        /// </summary>
        public static string AcceptTermsValidationErrorMustBeAccepted {
            get {
                return ResourceManager.GetString("AcceptTermsValidationErrorMustBeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The avatar image can&apos;t be larger than 5 MB and must be in the PNG, JPG or GIF format..
        /// </summary>
        public static string AvatarImageUploadHelp {
            get {
                return ResourceManager.GetString("AvatarImageUploadHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogger.
        /// </summary>
        public static string Blogger {
            get {
                return ResourceManager.GetString("Blogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to comment or reply to comments you need to.
        /// </summary>
        public static string CantComment1 {
            get {
                return ResourceManager.GetString("CantComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string CantComment2 {
            get {
                return ResourceManager.GetString("CantComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to comment you need to be part of the Commenter role..
        /// </summary>
        public static string CantCommentNotCommenter {
            get {
                return ResourceManager.GetString("CantCommentNotCommenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to collapse.
        /// </summary>
        public static string ClickToCollapse {
            get {
                return ResourceManager.GetString("ClickToCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to expand.
        /// </summary>
        public static string ClickToExpand {
            get {
                return ResourceManager.GetString("ClickToExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commenter.
        /// </summary>
        public static string Commenter {
            get {
                return ResourceManager.GetString("Commenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment(s).
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentsSection {
            get {
                return ResourceManager.GetString("CommentsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please leave a comment, your opinion is very important :).
        /// </summary>
        public static string CommentsSectionSmall {
            get {
                return ResourceManager.GetString("CommentsSectionSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password is wrong..
        /// </summary>
        public static string CurrentPasswordIsWrong {
            get {
                return ResourceManager.GetString("CurrentPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter current password..
        /// </summary>
        public static string CurrentPasswordValidationErrorRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit informations related to the current user.
        /// </summary>
        public static string EditDescription {
            get {
                return ResourceManager.GetString("EditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use. Maybe you already have an account, try to perform a sign in or change your password if you can&apos;t remember it..
        /// </summary>
        public static string EmailAddressValidationErrorAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAddressValidationErrorAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid email address..
        /// </summary>
        public static string EmailAddressValidationErrorNotValid {
            get {
                return ResourceManager.GetString("EmailAddressValidationErrorNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address..
        /// </summary>
        public static string EmailAddressValidationErrorRequired {
            get {
                return ResourceManager.GetString("EmailAddressValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter with the post content.
        /// </summary>
        public static string HomeNewEditContentValidationErrorRequired {
            get {
                return ResourceManager.GetString("HomeNewEditContentValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title for this post.
        /// </summary>
        public static string HomeNewEditTitleValidationErrorRequired {
            get {
                return ResourceManager.GetString("HomeNewEditTitleValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Confirmation.
        /// </summary>
        public static string NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differs from the provided new password..
        /// </summary>
        public static string NewPasswordConfirmationValidationErrorDiffers {
            get {
                return ResourceManager.GetString("NewPasswordConfirmationValidationErrorDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new password confirmation..
        /// </summary>
        public static string NewPasswordConfirmationValidationErrorRequired {
            get {
                return ResourceManager.GetString("NewPasswordConfirmationValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password is invalid..
        /// </summary>
        public static string NewPasswordValidationErrorInvalid {
            get {
                return ResourceManager.GetString("NewPasswordValidationErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password..
        /// </summary>
        public static string NewPasswordValidationErrorRequired {
            get {
                return ResourceManager.GetString("NewPasswordValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differs from the provided password..
        /// </summary>
        public static string PasswordConfirmationValidationErrorDiffers {
            get {
                return ResourceManager.GetString("PasswordConfirmationValidationErrorDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password confirmation..
        /// </summary>
        public static string PasswordConfirmationValidationErrorRequired {
            get {
                return ResourceManager.GetString("PasswordConfirmationValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid password is composed of at least one digit, one lower case character, one upper case character and a minimum of 6 characters..
        /// </summary>
        public static string PasswordHelp {
            get {
                return ResourceManager.GetString("PasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password is invalid..
        /// </summary>
        public static string PasswordValidationErrorInvalid {
            get {
                return ResourceManager.GetString("PasswordValidationErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        public static string PasswordValidationErrorRequired {
            get {
                return ResourceManager.GetString("PasswordValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post comment.
        /// </summary>
        public static string PostComment {
            get {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a comment.
        /// </summary>
        public static string PostCommentContentValidationErrorRequired {
            get {
                return ResourceManager.GetString("PostCommentContentValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to comment.
        /// </summary>
        public static string ReplyToComment {
            get {
                return ResourceManager.GetString("ReplyToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Home Page.
        /// </summary>
        public static string ReturnHome {
            get {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        public static string SaveEdits {
            get {
                return ResourceManager.GetString("SaveEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your credentials.
        /// </summary>
        public static string SignInDescription {
            get {
                return ResourceManager.GetString("SignInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a new account.
        /// </summary>
        public static string SignUpDescription {
            get {
                return ResourceManager.GetString("SignUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened during the user registration. Sorry....
        /// </summary>
        public static string SomethingHappenedUserRegistration {
            get {
                return ResourceManager.GetString("SomethingHappenedUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This avatar could not be found..
        /// </summary>
        public static string ThisAvatarCouldNotBeFoundException {
            get {
                return ResourceManager.GetString("ThisAvatarCouldNotBeFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This comment could not be found, maybe it was deleted..
        /// </summary>
        public static string ThisCommentCouldNotBeFoundException {
            get {
                return ResourceManager.GetString("ThisCommentCouldNotBeFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This post could not be found, maybe the URL is wrong or it was deleted..
        /// </summary>
        public static string ThisPostCouldNotBeFoundException {
            get {
                return ResourceManager.GetString("ThisPostCouldNotBeFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role does not exist..
        /// </summary>
        public static string ThisRoleDoesNotExist {
            get {
                return ResourceManager.GetString("ThisRoleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user could not be found, maybe it was deleted..
        /// </summary>
        public static string ThisUserCouldNotBeFoundException {
            get {
                return ResourceManager.GetString("ThisUserCouldNotBeFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect..
        /// </summary>
        public static string UserEditIncorrectPassword {
            get {
                return ResourceManager.GetString("UserEditIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username do not exist..
        /// </summary>
        public static string UsernameDoNotExist {
            get {
                return ResourceManager.GetString("UsernameDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already in use. Please choose another one..
        /// </summary>
        public static string UsernameValidationErrorAlreadyInUse {
            get {
                return ResourceManager.GetString("UsernameValidationErrorAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username need to be between 5 and 30 characters..
        /// </summary>
        public static string UsernameValidationErrorLength {
            get {
                return ResourceManager.GetString("UsernameValidationErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an username..
        /// </summary>
        public static string UsernameValidationErrorRequired {
            get {
                return ResourceManager.GetString("UsernameValidationErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user profile..
        /// </summary>
        public static string UserProfileEdit {
            get {
                return ResourceManager.GetString("UserProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string UserSignIn {
            get {
                return ResourceManager.GetString("UserSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username and/or password..
        /// </summary>
        public static string UserSignInError {
            get {
                return ResourceManager.GetString("UserSignInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string UserSignUp {
            get {
                return ResourceManager.GetString("UserSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a New Post.
        /// </summary>
        public static string WriteNewPost {
            get {
                return ResourceManager.GetString("WriteNewPost", resourceCulture);
            }
        }
    }
}
